#!/usr/bin/env python3
#
# muttiml -- HTML Mail Helper for Mutt
# Created: Marcus Butler <marcusb@marcusb.org>, 01-February-2021
#
# Copyright 2021 Marcus Butler
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#  1. Redistributions of source code must retain the above copyright notice,
#     this list of conditions and the following disclaimer.
#
#  2. Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
#
#  3. Neither the name of the copyright holder nor the names of its
#     contributors may be used to endorse or promote products derived from this
#     software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

from sys import exit, stdin
from tempfile import mkstemp
from os import system
import email
import quopri

processed = ''

raw_msg = ''

for line in stdin.readlines():
    raw_msg += line

msg = email.message_from_string(raw_msg)
type = msg.get_content_type()

if type == 'text/html':
    print("CTE: " + msg.get('Content-Transfer-Encoding'))
    
    if msg.get('Content-Transfer-Encoding') == 'quoted-printable':
        tmp = msg.get_payload().replace('=\r','').replace('\r','')
        processed = str(quopri.decodestring(tmp))
    else:
        processed = str(msg.get_payload().replace('\r',''))
elif type == 'text/plain':
    processed = msg.get_payload()
else:
    print("Cannot process " + type + "messages...")
    exit(1)

(id, file) = mkstemp(suffix='.html')

fd = open(file, 'w')
fd.write(processed.replace('\\n','').replace('\\t','').replace('\\\'','\''))
fd.close()

system("/usr/bin/open -a Safari " + file)
